// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBKOv3oN-a3R_DRx886b7hQi1YZlNcIvg',
    appId: '1:828901134891:web:623326114fa9cd4e19d06e',
    messagingSenderId: '828901134891',
    projectId: 'gym-coach-57a6c',
    authDomain: 'gym-coach-57a6c.firebaseapp.com',
    storageBucket: 'gym-coach-57a6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBco8f86MR1L2mxXgWfVRdkSN8ZbNHfpdc',
    appId: '1:828901134891:android:c4f9456407d8179619d06e',
    messagingSenderId: '828901134891',
    projectId: 'gym-coach-57a6c',
    storageBucket: 'gym-coach-57a6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnk0KS_5E4UYlprTlFoCP4-8yrH6P9c78',
    appId: '1:828901134891:ios:a6c5173ab9ed6a1019d06e',
    messagingSenderId: '828901134891',
    projectId: 'gym-coach-57a6c',
    storageBucket: 'gym-coach-57a6c.firebasestorage.app',
    iosClientId: '828901134891-9oaug77qbn7a9cd5m849b4f84gmche8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymCoachApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnk0KS_5E4UYlprTlFoCP4-8yrH6P9c78',
    appId: '1:828901134891:ios:a6c5173ab9ed6a1019d06e',
    messagingSenderId: '828901134891',
    projectId: 'gym-coach-57a6c',
    storageBucket: 'gym-coach-57a6c.firebasestorage.app',
    iosClientId: '828901134891-9oaug77qbn7a9cd5m849b4f84gmche8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymCoachApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBKOv3oN-a3R_DRx886b7hQi1YZlNcIvg',
    appId: '1:828901134891:web:7c17d225b4d5214919d06e',
    messagingSenderId: '828901134891',
    projectId: 'gym-coach-57a6c',
    authDomain: 'gym-coach-57a6c.firebaseapp.com',
    storageBucket: 'gym-coach-57a6c.firebasestorage.app',
  );

}